version: "3"

services:

  php-fpm:
    # build: docker/php-fpm
    image: interpol/php-fpm
    restart: always
    container_name: php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/php-fpm/php.ini-development:/usr/local/etc/php/php.ini
      # - ./docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini

  apache:
    image: httpd:alpine
    restart: always
    container_name: apache
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache2/extra/httpd-php.conf:/usr/local/apache2/conf/extra/httpd-php.conf
      - ./docker/apache2/extra/httpd-info.conf:/usr/local/apache2/conf/extra/httpd-info.conf
      # - ./docker/apache2/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - php-fpm

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl/server.crt:/ssl/server.crt
      - ./docker/ssl/server.key:/ssl/server.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache

  mysql:
    image: mariadb
    restart: always
    container_name: mariadb
    working_dir: /mariadb
    volumes:
      - ./mariadb:/var/lib/mysql/
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d
      - ./docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./docker/mariadb/mariadb.conf.d:/etc/mysql/mariadb.conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=my_pass
      - MYSQL_DATABASE=my_db
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # - MYSQL_USER=my_user
      # - MYSQL_PASSWORD=my_pass
    ports:
      - "3306:3306"
